name: Build AIX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build App Inventor Extension
        uses: ysfchn/build-appinventor-extension@v1.2
        with:
          input-directory: .
          output-directory: out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notificationstyle-aix
          path: out
