name: Build AIX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build AIX Extension
        id: build
        uses: pavi2410/AIX-Action@main
        with:
          source-dir: .
          package-name: com.jdl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: ${{ steps.build.outputs.extension-path }}
